<a href="https://colab.research.google.com/github/PurpleHyacinth120/ML-Lab/blob/main/ML_Lab_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr)
print(np.flip(arr))

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [9]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten('K'))
print(array1.flatten('F'))

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
if (arr1 == arr2).all() :
  print('Arrays are equal')
else :
  print('Arrays are not equal')

Arrays are equal


In [14]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
val, cnt = np.unique(x, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(x == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 5, 7, 8, 9]),)


In [13]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
val, cnt = np.unique(y, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(y == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 1, 2]),)
3 (array([4, 8, 9]),)


In [19]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis = 0))
print(np.sum(gfg, axis = 1))

45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [28]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print('Sum of diagonal elements of the matrix is\n', np.trace(n_array))
eigval, eigvect = np.linalg.eig(n_array)

Sum of diagonal elements of the matrix is
 176


In [29]:
print('Eigen values of the matrix are\n', eigval)

Eigen values of the matrix are
 [98.16835147 28.097044   49.73460452]


In [30]:

print('Eigen vectors of the matrix is\n', eigvect)

Eigen vectors of the matrix is
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [27]:
print('Inverse of the matrix is\n', np.linalg.inv(n_array))

Inverse of the matrix is
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [26]:
print('Determinant of the matrix is\n', np.linalg.det(n_array))

Determinant of the matrix is
 137180.0000000001


In [37]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(np.matmul(p, q))

[[16 19]
 [26 31]]


In [38]:
print(np.cov(p, q))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [39]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print(np.matmul(p, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [40]:
print(np.cov(p, q))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3