<a href="https://colab.research.google.com/github/PurpleHyacinth120/ML-Lab/blob/main/ML_Lab_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr)
print(np.flip(arr))

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten('K'))
print(array1.flatten('F'))

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
if (arr1 == arr2).all() :
  print('Arrays are equal')
else :
  print('Arrays are not equal')

Arrays are equal


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
val, cnt = np.unique(x, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(x == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 5, 7, 8, 9]),)


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
val, cnt = np.unique(y, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(y == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 1, 2]),)
3 (array([4, 8, 9]),)


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis = 0))
print(np.sum(gfg, axis = 1))

45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print('Sum of diagonal elements of the matrix is\n', np.trace(n_array))
eigval, eigvect = np.linalg.eig(n_array)

Sum of diagonal elements of the matrix is
 176


In [ ]:
print('Eigen values of the matrix are\n', eigval)

Eigen values of the matrix are
 [98.16835147 28.097044   49.73460452]


In [ ]:
print('Eigen vectors of the matrix is\n', eigvect)

Eigen vectors of the matrix is
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
print('Inverse of the matrix is\n', np.linalg.inv(n_array))

Inverse of the matrix is
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
print('Determinant of the matrix is\n', np.linalg.det(n_array))

Determinant of the matrix is
 137180.0000000001


In [ ]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(np.matmul(p, q))

[[16 19]
 [26 31]]


In [ ]:
print(np.cov(p, q))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print(np.matmul(p, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
print(np.cov(p, q))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a1 = np.array([[2, 3, 4], [3, 2, 9]])
a2 = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(a1, a2))

[[17 52]
 [13 62]]


In [ ]:
print(np.outer(a1, a2))

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
print(np.dstack(np.meshgrid(a1, a2).reshape(-1, 2)))

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
ar = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.absolute(ar))

[[1 2 3]
 [4 5 6]]


For each column

In [ ]:
#For each column
np.percentile(ar, 25, axis = 0)

array([-2.75, -0.25, -3.75])

In [ ]:
np.percentile(ar, 50, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.percentile(ar, 75, axis = 0)

array([-0.25,  3.25,  0.75])

For each row

In [ ]:
np.percentile(ar, 25, axis = 1)

array([-0.5, -5. ])

In [ ]:
np.percentile(ar, 50, axis = 1)

array([ 1., -4.])

In [ ]:
np.percentile(ar, 75, axis = 1)

array([2. , 0.5])

In [ ]:
np.percentile(ar, 25)

-3.5

In [ ]:
np.percentile(ar, 50)

-0.5

In [ ]:
np.percentile(ar, 75)

2.5

For each column

In [ ]:
np.mean(ar, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.median(ar, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.std(ar, axis = 0)

array([2.5, 3.5, 4.5])

In [ ]:
np.mean(ar, axis = 1)

array([ 0.66666667, -1.66666667])

In [ ]:
np.median(ar, axis = 1)

array([ 1., -4.])

In [ ]:
np.std(ar, axis = 1)

array([2.05480467, 4.78423336])

In [ ]:
np.mean(ar)

-0.5

In [ ]:
np.median(ar)

-0.5

In [ ]:
np.std(ar)

3.8622100754188224

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [ ]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [ ]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [ ]:
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
np.sort(array)

array([ 10,  16,  16,  52,  54,  62, 453])

ii. Indices of sorted array

In [ ]:
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6])

iii. 4 smallest elements

In [ ]:
array[np.argpartition(array, 4)[:4]]

array([16, 10, 16, 52])

iv. 5 largest elements

In [ ]:
array[np.argpartition(array, -5)[:5]]

array([10, 16, 16, 52, 62])

In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0, 5], dtype = object)
integer_arr = []
float_arr = []
for i in array :
    if np.equal(np.mod(i, 1), 0) :
        integer_arr.append(i)
    else:
        float_arr.append(i)
print(integer_arr)
print(float_arr)

[1.0, 2.0, 3.0, 2.0, 5]
[1.2, 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [ ]:
from PIL import Image

In [ ]:
def img_to_array(path):
  img = Image.open(path)
  if img.mode == 'RGB':
    arr = np.array(img)
    with open('rgb_image.txt', 'w') as f:
      for row in arr:
        np.savetxt(f, row, fmt='%d')
  elif img.mode == 'L':
    arr = np.array(img)
    with open('grey_scale_image.txt', 'w') as f:
      np.savetxt(f, arr, fmt='%d')

In [ ]:
imagepath = '/content/aachen_000005_000019_leftImg8bit_foggy_beta_0.02_fake_0.png'
img_to_array(imagepath)

In [ ]:
imagepath = '/content/gray_scale.jpeg'
img_to_array(imagepath)

(b) Load the saved file into jupyter notebook?

In [ ]:
np.loadtxt('rgb_image.txt')

array([[40., 49., 49.],
       [34., 47., 46.],
       [34., 46., 46.],
       ...,
       [42., 55., 49.],
       [39., 54., 47.],
       [41., 54., 47.]])

In [ ]:
np.loadtxt('grey_scale_image.txt')

array([[149., 152., 156., ...,  74.,  74.,  74.],
       [157., 159., 161., ...,  74.,  74.,  74.],
       [165., 167., 168., ...,  74.,  74.,  74.],
       ...,
       [192., 192., 192., ..., 190., 188., 187.],
       [192., 192., 192., ..., 190., 188., 187.],
       [192., 192., 192., ..., 190., 188., 187.]])

**Assignment 2**

In [ ]:
import pandas as pd

df = pd.DataFrame()
df['Name'] = ['Bob', 'Alice', 'Slavic', 'Vladosiya', 'is_this_fft']
df['Age'] = [15, 15, 25, 23, 31]
df['CFR'] = [2478, 2348, 1780, 1681, 3100]
# df.replace(15, 20)
# df.rename(columns = {'CFR':'MCFR'})
# print(df['Age'].value_counts())
# df.drop('Age', axis = 1)
# df.drop_duplicates()
df.groupby('Age')

In [ ]:
df = pd.read_csv('/content/AWCustomers.csv')

ndf = df.drop(df.columns[[0, 1, 2, 3, 4, 5, 12, 14, 16, 23]], axis=1)


In [ ]:
ndf

AddressLine1 AddressLine2            City  \
0          7090 C. Mount Hood          NaN      Wollongong   
1         3651 Willow Lake Rd          NaN         Shawnee   
2      1774 Tice Valley Blvd.          NaN     West Covina   
3             2103 Baldwin Dr          NaN       Liverpool   
4             Am Gallberg 234          NaN           Werne   
...                       ...          ...             ...   
18356      6627 Camelback Ct.          NaN        Coronado   
18357         9627 Kendall Rd          NaN  Port Macquarie   
18358       4364 Viera Avenue          NaN       Beaverton   
18359  3866 Mt. Everest Court          NaN       Vancouver   
18360     7870 Orangewood Dr.          NaN       Grossmont   

         StateProvinceName CountryRegionName PostalCode   BirthDate  \
0          New South Wales         Australia       2500  1987-11-13   
1         British Columbia            Canada    V9B 2C3  1972-07-21   
2               California     United States      91791  1985-11-09   
3                  England    United Kingdom     L4 4HB  1977-10-18   
4      Nordrhein-Westfalen           Germany      59368  1975-02-05   
...                    ...               ...        ...         ...   
18356           California     United States      92118  1990-11-11   
18357      New South Wales         Australia       2444  1992-10-13   
18358               Oregon     United States      97005  1983-11-24   
18359     British Columbia            Canada    V7L 4J4  1995-06-15   
18360           California     United States      91941  1986-03-26   

           Occupation Gender MaritalStatus  HomeOwnerFlag  NumberCarsOwned  \
0            Clerical      M             M              1                3   
1            Clerical      M             M              1                2   
2            Clerical      F             S              0                3   
3      Skilled Manual      M             M              1                2   
4      Skilled Manual      M             S              1                1   
...               ...    ...           ...            ...              ...   
18356  Skilled Manual      F             M              0                1   
18357  Skilled Manual      F             S              0                2   
18358  Skilled Manual      F             S              0                2   
18359        Clerical      F             S              0                0   
18360    Professional      F             M              1                2   

       NumberChildrenAtHome  TotalChildren  YearlyIncome  
0                         0              1         81916  
1                         1              2         81076  
2                         0              0         86387  
3                         1              2         61481  
4                         0              0         51804  
...                     ...            ...           ...  
18356                     0              2         52953  
18357                     0              0         60992  
18358                     0              0         51859  
18359                     0              0         87177  
18360                     0              0        136856  

[18361 rows x 15 columns]

from matplotlib import pyplot as plt
ndf['HomeOwnerFlag'].plot(kind='hist', bins=20, title='HomeOwnerFlag')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberCarsOwned'].plot(kind='hist', bins=20, title='NumberCarsOwned')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberChildrenAtHome'].plot(kind='hist', bins=20, title='NumberChildrenAtHome')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf['TotalChildren'].plot(kind='hist', bins=20, title='TotalChildren')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ndf.groupby('CountryRegionName').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ndf.groupby('Occupation').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ndf.groupby('Gender').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
ndf.groupby('MaritalStatus').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf.plot(kind='scatter', x='HomeOwnerFlag', y='NumberCarsOwned', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf.plot(kind='scatter', x='NumberCarsOwned', y='NumberChildrenAtHome', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf.plot(kind='scatter', x='NumberChildrenAtHome', y='TotalChildren', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf.plot(kind='scatter', x='TotalChildren', y='YearlyIncome', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['BirthDate']
  ys = series['HomeOwnerFlag']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ndf.sort_values('BirthDate', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('CountryRegionName')):
  _plot_series(series, series_name, i)
  fig.legend(title='CountryRegionName', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('BirthDate')
_ = plt.ylabel('HomeOwnerFlag')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['BirthDate']
  ys = series['HomeOwnerFlag']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ndf.sort_values('BirthDate', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Occupation')):
  _plot_series(series, series_name, i)
  fig.legend(title='Occupation', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('BirthDate')
_ = plt.ylabel('HomeOwnerFlag')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['BirthDate']
  ys = series['HomeOwnerFlag']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ndf.sort_values('BirthDate', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('Gender')):
  _plot_series(series, series_name, i)
  fig.legend(title='Gender', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('BirthDate')
_ = plt.ylabel('HomeOwnerFlag')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['BirthDate']
  ys = series['HomeOwnerFlag']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = ndf.sort_values('BirthDate', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('MaritalStatus')):
  _plot_series(series, series_name, i)
  fig.legend(title='MaritalStatus', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('BirthDate')
_ = plt.ylabel('HomeOwnerFlag')

from matplotlib import pyplot as plt
ndf['HomeOwnerFlag'].plot(kind='line', figsize=(8, 4), title='HomeOwnerFlag')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberCarsOwned'].plot(kind='line', figsize=(8, 4), title='NumberCarsOwned')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberChildrenAtHome'].plot(kind='line', figsize=(8, 4), title='NumberChildrenAtHome')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
ndf['TotalChildren'].plot(kind='line', figsize=(8, 4), title='TotalChildren')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Occupation'].value_counts()
    for x_label, grp in ndf.groupby('CountryRegionName')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('CountryRegionName')
_ = plt.ylabel('Occupation')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['Gender'].value_counts()
    for x_label, grp in ndf.groupby('Occupation')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Occupation')
_ = plt.ylabel('Gender')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['MaritalStatus'].value_counts()
    for x_label, grp in ndf.groupby('Gender')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Gender')
_ = plt.ylabel('MaritalStatus')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ndf['CountryRegionName'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ndf, x='HomeOwnerFlag', y='CountryRegionName', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ndf['Occupation'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ndf, x='HomeOwnerFlag', y='Occupation', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ndf['Gender'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ndf, x='HomeOwnerFlag', y='Gender', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(ndf['MaritalStatus'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(ndf, x='HomeOwnerFlag', y='MaritalStatus', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
ndf['HomeOwnerFlag'].plot(kind='hist', bins=20, title='HomeOwnerFlag')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberCarsOwned'].plot(kind='hist', bins=20, title='NumberCarsOwned')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
ndf['NumberChildrenAtHome'].plot(kind='hist', bins=20, title='NumberChildrenAtHome')
plt.gca().spines[['top', 'right',]].set_visible(False)