<a href="https://colab.research.google.com/github/PurpleHyacinth120/ML-Lab/blob/main/ML_Lab_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(arr)
print(np.flip(arr))

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print(array1.flatten('K'))
print(array1.flatten('F'))

[1 2 3 2 4 5 1 2 3]
[1 2 1 2 4 2 3 5 3]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
if (arr1 == arr2).all() :
  print('Arrays are equal')
else :
  print('Arrays are not equal')

Arrays are equal


In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
val, cnt = np.unique(x, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(x == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 5, 7, 8, 9]),)


In [ ]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
val, cnt = np.unique(y, return_counts = True)
ind = np.argmax(cnt)
mx = cnt[ind]
mfv = val[np.where(cnt == mx)]
idx = []
for p in mfv:
  idx.append(np.where(y == p))
for i, mf in enumerate(mfv):
  print(mfv[i], idx[i])

1 (array([0, 1, 2]),)
3 (array([4, 8, 9]),)


In [ ]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(np.sum(gfg))
print(np.sum(gfg, axis = 0))
print(np.sum(gfg, axis = 1))

45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [ ]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print('Sum of diagonal elements of the matrix is\n', np.trace(n_array))
eigval, eigvect = np.linalg.eig(n_array)

Sum of diagonal elements of the matrix is
 176


In [ ]:
print('Eigen values of the matrix are\n', eigval)

Eigen values of the matrix are
 [98.16835147 28.097044   49.73460452]


In [ ]:
print('Eigen vectors of the matrix is\n', eigvect)

Eigen vectors of the matrix is
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


In [ ]:
print('Inverse of the matrix is\n', np.linalg.inv(n_array))

Inverse of the matrix is
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


In [ ]:
print('Determinant of the matrix is\n', np.linalg.det(n_array))

Determinant of the matrix is
 137180.0000000001


In [ ]:
p = [[1, 2], [2, 3]]
q = [[4, 5], [6, 7]]
print(np.matmul(p, q))

[[16 19]
 [26 31]]


In [ ]:
print(np.cov(p, q))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [ ]:
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
print(np.matmul(p, q))

[[16 19  5]
 [26 31  8]
 [46 55 14]]


In [ ]:
print(np.cov(p, q))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [ ]:
a1 = np.array([[2, 3, 4], [3, 2, 9]])
a2 = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(a1, a2))

[[17 52]
 [13 62]]


In [ ]:
print(np.outer(a1, a2))

[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [ ]:
print(np.dstack(np.meshgrid(a1, a2).reshape(-1, 2)))

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
ar = np.array([[1, -2, 3],[-4, 5, -6]])
print(np.absolute(ar))

[[1 2 3]
 [4 5 6]]


For each column

In [ ]:
#For each column
np.percentile(ar, 25, axis = 0)

array([-2.75, -0.25, -3.75])

In [ ]:
np.percentile(ar, 50, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.percentile(ar, 75, axis = 0)

array([-0.25,  3.25,  0.75])

For each row

In [ ]:
np.percentile(ar, 25, axis = 1)

array([-0.5, -5. ])

In [ ]:
np.percentile(ar, 50, axis = 1)

array([ 1., -4.])

In [ ]:
np.percentile(ar, 75, axis = 1)

array([2. , 0.5])

In [ ]:
np.percentile(ar, 25)

-3.5

In [ ]:
np.percentile(ar, 50)

-0.5

In [ ]:
np.percentile(ar, 75)

2.5

For each column

In [ ]:
np.mean(ar, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.median(ar, axis = 0)

array([-1.5,  1.5, -1.5])

In [ ]:
np.std(ar, axis = 0)

array([2.5, 3.5, 4.5])

In [ ]:
np.mean(ar, axis = 1)

array([ 0.66666667, -1.66666667])

In [ ]:
np.median(ar, axis = 1)

array([ 1., -4.])

In [ ]:
np.std(ar, axis = 1)

array([2.05480467, 4.78423336])

In [ ]:
np.mean(ar)

-0.5

In [ ]:
np.median(ar)

-0.5

In [ ]:
np.std(ar)

3.8622100754188224

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [ ]:
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [ ]:
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [ ]:
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

Q3: Based on Searching and Sorting
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

i. Sorted array

In [ ]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
np.sort(array)

array([ 10,  16,  16,  52,  54,  62, 453])

ii. Indices of sorted array

In [ ]:
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6])

iii. 4 smallest elements

In [ ]:
array[np.argpartition(array, 4)[:4]]

array([16, 10, 16, 52])

iv. 5 largest elements

In [ ]:
array[np.argpartition(array, -5)[:5]]

array([10, 16, 16, 52, 62])

In [ ]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0, 5], dtype = object)
integer_arr = []
float_arr = []
for i in array :
    if np.equal(np.mod(i, 1), 0) :
        integer_arr.append(i)
    else:
        float_arr.append(i)
print(integer_arr)
print(float_arr)

[1.0, 2.0, 3.0, 2.0, 5]
[1.2, 2.2]


Q4:
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [ ]:
from PIL import Image

In [ ]:
def img_to_array(path):
  img = Image.open(path)
  if img.mode == 'RGB':
    arr = np.array(img)
    with open('rgb_image.txt', 'w') as f:
      for row in arr:
        np.savetxt(f, row, fmt='%d')
  elif img.mode == 'L':
    arr = np.array(img)
    with open('grey_scale_image.txt', 'w') as f:
      np.savetxt(f, arr, fmt='%d')

In [ ]:
imagepath = '/content/aachen_000005_000019_leftImg8bit_foggy_beta_0.02_fake_0.png'
img_to_array(imagepath)

In [ ]:
imagepath = '/content/gray_scale.jpeg'
img_to_array(imagepath)

(b) Load the saved file into jupyter notebook?

In [ ]:
np.loadtxt('rgb_image.txt')

array([[40., 49., 49.],
       [34., 47., 46.],
       [34., 46., 46.],
       ...,
       [42., 55., 49.],
       [39., 54., 47.],
       [41., 54., 47.]])

In [ ]:
np.loadtxt('grey_scale_image.txt')

array([[149., 152., 156., ...,  74.,  74.,  74.],
       [157., 159., 161., ...,  74.,  74.,  74.],
       [165., 167., 168., ...,  74.,  74.,  74.],
       ...,
       [192., 192., 192., ..., 190., 188., 187.],
       [192., 192., 192., ..., 190., 188., 187.],
       [192., 192., 192., ..., 190., 188., 187.]])